config/routes.rb
Depot::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"

  get "products/index"

  root :to => 'Store#index'

  resources :products

end

app/models/cart.rb
class Cart
  include Mongoid::Document

  has_many :line_items, dependent: :destroy

  def add_product(product)
    current_item = find_by_product_id(line_items, product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product: product)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  private

  def find_by_product_id line_items, product_id
    line_items.each {|item|
      return item if item.product.id == product_id
    }
    nil
  end

end

app/models/line_item.rb
class LineItem
  include Mongoid::Document
  belongs_to :product
  belongs_to :cart

  field :quantity, type: Integer, default: 1

  def total_price
    product.price * quantity
  end
end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  field :title, type: String
  field :description, type: String
  field :image_url, type: String
  field :price, type: Float

  has_many :line_items

  before_destroy :ensure_not_referenced_by_any_line_item

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true

  private
  def ensure_not_referenced_by_any_line_item
    return true if line_items.empty?
    errors.add(:base, 'Line Items present')
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_cart
    Cart.find(session[:cart_id] || 0)
  rescue Mongoid::Errors::DocumentNotFound
    cart = Cart.create
    session[:cart_id] = cart.id
    cart
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy

    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_index_path, notice: "Your cart is currently empty" }
      format.json { head :no_content }
    end
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    begin
      product = Product.find(params[:product_id])
      @line_item = @cart.add_product(product)
    rescue Mongoid::Errors::DocumentNotFound
      @line_item = LineItem.new
    end


    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_path }
        format.js { @current_item = @line_item }
        format.json { render json: @line_item, status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    product_request = params[:product]
    product = Product.new(product_request)
    if product.save
      redirect_to :action => :show, :id => product.id
    else
      render :action => 'new'
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def show
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    product = params[:product]
    if @product.update_attributes(product)
      redirect_to(product_path)
    else
        render edit_product_path(@product.id)
    end
  end

  def destroy
    product = Product.find(params[:id])
    product.destroy
    redirect_to products_path
  end

end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
    @products = Product.all.sort(title: 1)
    @cart = current_cart
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/carts/_cart.html.haml
- unless cart.line_items.empty?
  .carts
    %h2
      Your Cart
    %table
      = render(cart.line_items)
      %tr.total_line
        %td(colspan="2")
          Total
        %td.total_cell= number_to_currency(cart.total_price)

    = button_to "Empty Cart", cart, method: :delete, confirm: "Are you sure?"

app/views/carts/_form.html.haml
= form_for @cart do |f|
  -if @cart.errors.any?
    #error_explanation
      %h2= "#{pluralize(@cart.errors.count, "error")} prohibited this cart from being saved:"
      %ul
        - @cart.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/carts/edit.html.haml
%h1 Editing cart

= render 'form'

= link_to 'Show', @cart
\|
= link_to 'Back', carts_path

app/views/carts/index.html.haml
%h1 Listing carts

%table
  %tr
    %th
    %th
    %th

  - @carts.each do |cart|
    %tr
      %td= link_to 'Show', cart
      %td= link_to 'Edit', edit_cart_path(cart)
      %td= link_to 'Destroy', cart, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Cart', new_cart_path

app/views/carts/new.html.haml
%h1 New cart

= render 'form'

= link_to 'Back', carts_path

app/views/carts/show.html.haml
- if notice
  %p#notice= notice

= render(@cart)

app/views/layouts/application.html.haml
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
    %title= content_for?(:title) ? yield(:title) : "Books Online Store"
    %meta{:content => content_for?(:description) ? yield(:description) : "App_Name", :name => "description"}
    = stylesheet_link_tag :application, :media => "all"
    = javascript_include_tag :application
    = csrf_meta_tags
    = yield(:head)
  %body
    #banner
      = image_tag("rails.png")
      MyBook Shelf
    .columns
      .side
        - if @cart
          #cart(style="#{@cart.line_items.empty? ? 'display: none' : 'display: block' }" )
            = render(@cart)
        %ul
          %li link1
          %li link2
      #container.container
        %header
        #main{:role => "main"}
          = yield
        %footer

app/views/line_items/_form.html.haml
= form_for @line_item do |f|
  -if @line_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@line_item.errors.count, "error")} prohibited this line_item from being saved:"
      %ul
        - @line_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product_id
    = f.number_field :product_id
  .field
    = f.label :cart_id
    = f.number_field :cart_id
  .actions
    = f.submit 'Save'

app/views/line_items/_line_item.html.haml
%tr{:id => (line_item == @current_item) ? "current_item" : false}
  %td= "#{line_item.quantity} X"
  %td= line_item.product.title
  %td.item_price= number_to_currency(line_item.total_price)

app/views/line_items/create.js.haml
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }
else $('#cart').show()
$('#cart').html("#{j render @cart}");

$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);

app/views/line_items/edit.html.haml
%h1 Editing line_item

= render 'form'

= link_to 'Show', @line_item
\|
= link_to 'Back', line_items_path

app/views/line_items/index.html.haml
%h1 Listing line_items

%table
  %tr
    %th Product
    %th Cart
    %th
    %th
    %th

  - @line_items.each do |line_item|
    %tr
      %td= line_item.product_id
      %td= line_item.cart_id
      %td= link_to 'Show', line_item
      %td= link_to 'Edit', edit_line_item_path(line_item)
      %td= link_to 'Destroy', line_item, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Line item', new_line_item_path

app/views/line_items/new.html.haml
%h1 New line_item

= render 'form'

= link_to 'Back', line_items_path

app/views/line_items/show.html.haml
%p#notice= notice

%p
  %b Product:
  = @line_item.product_id
%p
  %b Cart:
  = @line_item.cart_id

= link_to 'Edit', edit_line_item_path(@line_item)
\|
= link_to 'Back', line_items_path

app/views/products/edit.html.haml
= form_for :product, :url => product_path, :html => { :method => :put } do |form|
  %ul
    %li
      = form.label "Title"
      = form.text_field "title"
    %li
      = form.label "Description"
    %p
      = form.text_area "description"
    %li
      = form.label "Price"
      = form.text_field "price"
    %li
      = form.label "Image Url"
      = form.text_field "image_url"
    %p
      = form.submit "Save Product"

app/views/products/index.html.haml
%h1 Products

.products
  %table
    - @products.each do |product|
      %tr[product]

        %td= image_tag(product.image_url, class: 'list_image')
        %td.list_description
          %dl
            %dt= product.title
            %dd= truncate(strip_tags(product.description), length: 80)

        %td.list_actions
          #{ link_to 'View', product_path(product)}
          #{ link_to 'Edit', edit_product_path(product.id)}
          #{ link_to 'Destroy', {action:'destroy', controller:'products', id: product.id}, method: 'delete'}
  %br
    Add #{ link_to 'New Product', '/products/new'}

app/views/products/new.html.haml
= form_for :product, :url => products_path, :html => { :method => :post } do |form|
  %ul
    %li
      = form.label "Title"
      = form.text_field "title"
    %li
      = form.label "Description"
    %p
      = form.text_area "description"
    %li
      = form.label "Price"
      = form.text_field "price"
    %li
      = form.label "Image Url"
      = form.text_field "image_url"
    %p
      = form.submit "Create Product"
-#
-#= form_for(action=products_path method='POST')
-#  %label
-#    %b Title :
-#  %input(type='text' name='title' value="")
-#  %input(type='submit' value="Create Product" )

app/views/products/show.html.haml
%h1= @product.title

%ul#product_details
  %li= @product.description
  %li= @product.price
  %img(src="#{@product.image_url}")

app/views/store/index.html.haml
- if notice
  %p#notice= notice
.store
  %h1
    Your Catalog
  - @products.each do |product|
    .entry
      = image_tag(product.image_url)
      %h3= product.title
      .description
        = sanitize(product.description)
      .price_line
        %span.price= number_to_currency(product.price)
        = button_to 'Add to Cart', line_items_path(product_id: product.id), remote: true